spring:
  application:
    name: "helpdesk"

  datasource:
    url: jdbc:mysql://localhost:3306/helpdesk
    username: root
    password: Anjali7944
    driver-class-name: com.mysql.cj.jdbc.Driver

    #hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




spring.ai.openai.api-key: ${groq_api}
spring.ai.openai.base-url: https://api.groq.com/openai
spring.ai.openai.chat.options.model: "openai/gpt-oss-20b"



server:
  port: 8080

logging:
    level:
       org:
         springframework:
                       ai:
                         chat:
                            client:
                                advisor: DEBUG










